apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmDemo.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "helmDemo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "helmDemo.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            successThreshold: 1
