{{- if .Values.ingress.enabled -}}
{{- $fullName := include "helmDemo.name" . -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 80
            pathType: Prefix
            path: /

{{- end }}
